# Generated by Django 5.2.9 on 2025-12-09 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome do evento/show', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detalhes do evento', null=True)),
                ('location', models.CharField(help_text='Local do show', max_length=300)),
                ('venue_contact', models.CharField(blank=True, help_text='Contato do local', max_length=200, null=True)),
                ('event_date', models.DateField(help_text='Data do evento')),
                ('start_time', models.TimeField(help_text='Hora de início')),
                ('end_time', models.TimeField(help_text='Hora de término')),
                ('start_datetime', models.DateTimeField(help_text='Data/hora início completa')),
                ('end_datetime', models.DateTimeField(help_text='Data/hora fim completa')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do cachê', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposta Enviada'), ('approved', 'Aprovada pelo Líder'), ('rejected', 'Rejeitada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='proposed', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-event_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('vocal', 'Vocal'), ('guitar', 'Guitarra'), ('bass', 'Baixo'), ('drums', 'Bateria'), ('keyboard', 'Teclado'), ('other', 'Outro')], max_length=20)),
                ('role', models.CharField(choices=[('member', 'Membro'), ('leader', 'Líder/Aprovador')], default='member', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Músico',
                'verbose_name_plural': 'Músicos',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('pending', 'Pendente'), ('available', 'Disponível'), ('unavailable', 'Indisponível'), ('maybe', 'Talvez')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a disponibilidade', null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='agenda.event')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='agenda.musician')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['event__event_date', 'musician__user__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date', 'status'], name='agenda_even_event_d_d71d26_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='agenda_even_status_520661_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('musician', 'event')},
        ),
    ]
