# Generated by Django 5.2.9 on 2025-12-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_solo',
            field=models.BooleanField(default=False, help_text='Indica se é um show solo (sem necessidade de aprovação do líder)'),
        ),
        migrations.CreateModel(
            name='LeaderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data disponível')),
                ('start_time', models.TimeField(help_text='Hora de início da disponibilidade')),
                ('end_time', models.TimeField(help_text='Hora de término da disponibilidade')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a disponibilidade', null=True)),
                ('start_datetime', models.DateTimeField(help_text='Data/hora início completa')),
                ('end_datetime', models.DateTimeField(help_text='Data/hora fim completa')),
                ('is_active', models.BooleanField(default=True, help_text='Se False, a disponibilidade foi removida/cancelada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(help_text='Líder que cadastrou a disponibilidade', limit_choices_to={'role': 'leader'}, on_delete=django.db.models.deletion.CASCADE, related_name='leader_availabilities', to='agenda.musician')),
            ],
            options={
                'verbose_name': 'Disponibilidade do Líder',
                'verbose_name_plural': 'Disponibilidades do Líder',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='agenda_lead_date_9b23a6_idx'), models.Index(fields=['leader', 'date'], name='agenda_lead_leader__3edecd_idx')],
            },
        ),
    ]
