# Generated by Django 5.2.9 on 2025-12-11 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_event_is_solo_leaderavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='response',
            field=models.CharField(choices=[('pending', 'Pendente'), ('available', 'Disponível'), ('unavailable', 'Indisponível'), ('maybe', 'Talvez')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor do cachê', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Valor do cachê não pode ser negativo.')]),
        ),
    ]
