# Generated by Django 5.2.9 on 2025-12-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_eventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposta Enviada'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='proposed', max_length=20),
        ),
    ]
