# Generated by Django 5.2.9 on 2025-12-13 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderavailability',
            name='leader',
            field=models.ForeignKey(help_text='Músico que cadastrou a disponibilidade', on_delete=django.db.models.deletion.CASCADE, related_name='leader_availabilities', to='agenda.musician'),
        ),
    ]
