# Generated by Django 5.2.9 on 2025-12-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_leaderavailability_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
