# Generated by Django 5.2.9 on 2025-12-14

from django.db import migrations


def update_sara_contacts(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Musician = apps.get_model('agenda', 'Musician')

    try:
        user = User.objects.get(username='sara')
    except User.DoesNotExist:
        return

    user.email = 'saram.carmo@hotmail.com'
    user.save(update_fields=['email'])

    try:
        musician = Musician.objects.get(user=user)
    except Musician.DoesNotExist:
        return

    musician.phone = '(17)99193-3859'
    musician.instagram = '@saracarmocantora'
    musician.bio = 'Vocalista e violonista - contrata músicos para apresentações'
    musician.save(update_fields=['phone', 'instagram', 'bio'])


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_musician_instagram'),
    ]

    operations = [
        migrations.RunPython(update_sara_contacts, migrations.RunPython.noop),
    ]
