# Generated by Django 5.2.9 on 2025-12-14

from django.db import migrations


def update_roberto_arthur_contacts(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Musician = apps.get_model('agenda', 'Musician')

    updates = [
        {
            'username': 'roberto',
            'email': 'riguimaandroid@gmail.com',
            'phone': '(34) 99174-3948',
            'instagram': '@roberto.guimaraes.299',
        },
        {
            'username': 'arthur',
            'email': 'catsinthegarden01@gmail.com',
            'phone': '(34) 98811-5465',
            'instagram': '@arthuraraujo07',
        },
    ]

    for entry in updates:
        try:
            user = User.objects.get(username=entry['username'])
        except User.DoesNotExist:
            continue

        user.email = entry['email']
        user.save(update_fields=['email'])

        try:
            musician = Musician.objects.get(user=user)
        except Musician.DoesNotExist:
            continue

        musician.phone = entry['phone']
        musician.instagram = entry['instagram']
        musician.save(update_fields=['phone', 'instagram'])


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_update_sara_contact'),
    ]

    operations = [
        migrations.RunPython(update_roberto_arthur_contacts, migrations.RunPython.noop),
    ]
