# Generated by Django 5.2.9 on 2025-12-15 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_org(apps, schema_editor):
    Organization = apps.get_model('agenda', 'Organization')
    Membership = apps.get_model('agenda', 'Membership')
    Musician = apps.get_model('agenda', 'Musician')
    Event = apps.get_model('agenda', 'Event')
    LeaderAvailability = apps.get_model('agenda', 'LeaderAvailability')
    User = apps.get_model('auth', 'User')

    org, _ = Organization.objects.get_or_create(
        name='Banda Principal',
        defaults={'subscription_status': 'active'}
    )

    owner = User.objects.filter(username='roberto').first() or User.objects.first()
    if owner:
        org.owner = owner
        org.save(update_fields=['owner'])
        Membership.objects.get_or_create(user=owner, organization=org, defaults={'role': 'owner', 'status': 'active'})

    for username in ['sara', 'arthur']:
        user = User.objects.filter(username=username).first()
        if user:
            Membership.objects.get_or_create(user=user, organization=org, defaults={'role': 'member', 'status': 'active'})

    Musician.objects.filter(organization__isnull=True).update(organization=org)
    Event.objects.filter(organization__isnull=True).update(organization=org)
    LeaderAvailability.objects.filter(organization__isnull=True).update(organization=org)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_update_roberto_arthur_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('subscription_status', models.CharField(default='active', max_length=30)),
                ('plan_id', models.CharField(blank=True, max_length=50, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agenda.organization'),
        ),
        migrations.AddField(
            model_name='leaderavailability',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_availabilities', to='agenda.organization'),
        ),
        migrations.AddField(
            model_name='musician',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musicians', to='agenda.organization'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('invited', 'Convidado'), ('suspended', 'Suspenso')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='agenda.organization')),
            ],
            options={
                'verbose_name': 'Membro da organização',
                'verbose_name_plural': 'Membros das organizações',
                'ordering': ['organization__name', 'user__username'],
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.RunPython(seed_default_org, migrations.RunPython.noop),
    ]
