# Generated by Django 5.2.9 on 2025-12-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_organization_event_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderavailability',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Indica se outros músicos podem ver esta disponibilidade'),
        ),
    ]
