# Generated by Django 5.2.9 on 2025-12-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_leaderavailability_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Média de avaliações recebidas (1-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='musician',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, help_text='Total de avaliações recebidas'),
        ),
        migrations.CreateModel(
            name='EventInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('vocal', 'Vocal'), ('guitar', 'Guitarra'), ('bass', 'Baixo'), ('drums', 'Bateria'), ('keyboard', 'Teclado'), ('other', 'Outro')], help_text='Tipo de instrumento necessário', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantidade de músicos deste instrumento')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_instruments', to='agenda.event')),
            ],
            options={
                'verbose_name': 'Instrumento do Evento',
                'verbose_name_plural': 'Instrumentos do Evento',
                'ordering': ['instrument'],
                'unique_together': {('event', 'instrument')},
            },
        ),
        migrations.CreateModel(
            name='MusicianRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Nota de 1 a 5 estrelas')),
                ('comment', models.TextField(blank=True, help_text='Comentário opcional sobre o músico', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Evento relacionado à avaliação', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='agenda.event')),
                ('musician', models.ForeignKey(help_text='Músico avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='agenda.musician')),
                ('rated_by', models.ForeignKey(help_text='Usuário que fez a avaliação', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de Músico',
                'verbose_name_plural': 'Avaliações de Músicos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['musician', 'rating'], name='agenda_musi_musicia_b16f2f_idx')],
                'unique_together': {('event', 'musician', 'rated_by')},
            },
        ),
    ]
