# Generated by Django 5.2.9 on 2025-12-16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_replace_other_with_percussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstrument',
            name='instrument',
            field=models.CharField(
                choices=[
                    ('vocal', 'Vocal'),
                    ('guitar', 'Guitarra'),
                    ('bass', 'Baixo'),
                    ('drums', 'Bateria'),
                    ('keyboard', 'Teclado'),
                    ('percussion', 'Percussão/Outros'),
                ],
                help_text='Tipo de instrumento necessário',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(
                choices=[
                    ('vocal', 'Vocal'),
                    ('guitar', 'Guitarra'),
                    ('bass', 'Baixo'),
                    ('drums', 'Bateria'),
                    ('keyboard', 'Teclado'),
                    ('percussion', 'Percussão/Outros'),
                ],
                max_length=20,
            ),
        ),
    ]
