# Generated by Django 5.2.9 on 2025-12-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_connections_and_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(help_text='Senha hasheada', max_length=255)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('instrument', models.CharField(blank=True, choices=[('vocal', 'Vocal'), ('guitar', 'Guitarra/Violão'), ('bass', 'Baixo'), ('drums', 'Bateria'), ('keyboard', 'Teclado'), ('percussion', 'Percussão/Outros')], max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_email', 'Aguardando verificação de email'), ('email_verified', 'Email verificado - Aguardando pagamento'), ('payment_pending', 'Pagamento em processamento'), ('completed', 'Cadastro concluído'), ('expired', 'Expirado')], default='pending_email', max_length=20)),
                ('email_token', models.CharField(help_text='Token de verificação de email', max_length=64, unique=True)),
                ('payment_token', models.CharField(blank=True, help_text='Token de pagamento', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Data de expiração do cadastro pendente')),
            ],
            options={
                'verbose_name': 'Cadastro Pendente',
                'verbose_name_plural': 'Cadastros Pendentes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='agenda_pend_email_3bb5f5_idx'), models.Index(fields=['email_token'], name='agenda_pend_email_t_17a41b_idx'), models.Index(fields=['payment_token'], name='agenda_pend_payment_672213_idx'), models.Index(fields=['status'], name='agenda_pend_status_190336_idx')],
            },
        ),
    ]
