# Generated by Django 5.2.9 on 2025-12-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_allow_custom_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text='Data de término da assinatura', null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensal'), ('annual', 'Anual')], help_text='Plano de assinatura', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Ativa'), ('canceled', 'Cancelada'), ('past_due', 'Pagamento Pendente')], default='active', help_text='Status da assinatura Stripe', max_length=20),
        ),
    ]
