# Generated by Django 5.2.9 on 2025-12-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0018_stripe_subscription_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='Data de término do período de teste', null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='Data de início do período de teste', null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Período de Teste'), ('active', 'Ativa'), ('canceled', 'Cancelada'), ('past_due', 'Pagamento Pendente'), ('expired', 'Expirada')], default='trial', help_text='Status da assinatura', max_length=20),
        ),
    ]
