# Generated by Django 5.2.9 on 2025-12-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_add_multi_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[('created', 'Criado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('availability', 'Disponibilidade'), ('notification', 'Notificacao')], max_length=30),
        ),
    ]
