# Generated by Django 5.2.9 on 2026-01-10 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0021_alter_eventlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderavailability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Disponibilidade', 'verbose_name_plural': 'Disponibilidades'},
        ),
        migrations.AddField(
            model_name='musician',
            name='base_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor base de cachê do músico', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Valor do cachê não pode ser negativo.')]),
        ),
        migrations.AddField(
            model_name='musician',
            name='equipment_items',
            field=models.JSONField(blank=True, default=list, help_text='Lista de equipamentos/serviços com valores'),
        ),
        migrations.AddField(
            model_name='musician',
            name='travel_fee_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor cobrado por km deslocado', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, message='Valor por km não pode ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_solo',
            field=models.BooleanField(default=False, help_text='Indica se é um show solo (confirmação automática)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposta Enviada'), ('approved', 'Confirmado'), ('rejected', 'Rejeitado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='musician',
            name='role',
            field=models.CharField(choices=[('member', 'Membro')], default='member', max_length=20),
        ),
    ]
