# Generated by Django 5.2.8 on 2026-01-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_alter_leaderavailability_options_musician_base_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade onde o músico reside', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
