# Generated by Django 5.2.8 on 2026-01-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0023_add_city_to_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='state',
            field=models.CharField(blank=True, help_text='UF (sigla do estado)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
