# Generated by Django 5.2.8 on 2026-01-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0024_add_state_to_musician'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp com máscara (11) 99999-9999', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
