# Generated by Django 5.2.8 on 2026-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_add_social_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil do músico', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='musician',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Imagem de capa do perfil', null=True, upload_to='covers/'),
        ),
    ]
