# Generated by Django 5.2.8 on 2026-01-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0027_add_email_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(choices=[('follow', 'Seguir favorito'), ('call_later', 'Ligar depois'), ('recommend', 'Indicar para vaga'), ('played_with', 'Já toquei com')], db_index=True, default='follow', max_length=20),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['follower', 'created_at'], name='agenda_conn_followe_4f22a4_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['target', 'created_at'], name='agenda_conn_target__d3e6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['follower', 'target'], name='agenda_conn_followe_ca09bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('follower', 'target', 'connection_type'), name='uniq_connection_follower_target_type'),
        ),
    ]
