# Generated by Django 5.2.8 on 2026-01-28 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0028_alter_connection_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email de contato', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nome do responsável', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da empresa/organização', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_sponsor',
            field=models.BooleanField(default=False, help_text='É patrocinador da plataforma'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da organização', null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('band', 'Banda/Grupo'), ('company', 'Empresa'), ('venue', 'Casa de Shows')], default='band', help_text='Tipo de organização', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sponsor_tier',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Prata'), ('gold', 'Ouro')], help_text='Nível de patrocínio', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, help_text='UF', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Site da empresa', null=True),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Assunto da mensagem', max_length=200)),
                ('message', models.TextField(help_text='Mensagem/descrição do evento')),
                ('event_date', models.DateField(blank=True, help_text='Data do evento (opcional)', null=True)),
                ('event_location', models.CharField(blank=True, help_text='Local do evento', max_length=200, null=True)),
                ('budget_range', models.CharField(blank=True, help_text='Faixa de orçamento', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('read', 'Lido'), ('replied', 'Respondido'), ('archived', 'Arquivado')], default='pending', max_length=20)),
                ('reply_message', models.TextField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contact_requests', to='agenda.organization')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contact_requests', to=settings.AUTH_USER_MODEL)),
                ('to_musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contact_requests', to='agenda.musician')),
            ],
            options={
                'verbose_name': 'Solicitação de Contato',
                'verbose_name_plural': 'Solicitações de Contato',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_musician', 'status'], name='agenda_cont_to_musi_a2f3e6_idx'), models.Index(fields=['from_organization', 'created_at'], name='agenda_cont_from_or_d067e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MusicianRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('instrument', models.CharField(help_text='Instrumento principal', max_length=100)),
                ('instruments', models.JSONField(blank=True, default=list, help_text='Lista de instrumentos')),
                ('bio', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas do admin sobre a solicitação', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('invite_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invite_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_musician_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Músico',
                'verbose_name_plural': 'Solicitações de Músicos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='agenda_musi_status_a95dad_idx'), models.Index(fields=['invite_token'], name='agenda_musi_invite__5c670f_idx'), models.Index(fields=['email'], name='agenda_musi_email_edc003_idx')],
            },
        ),
    ]
