# Generated by Django 5.2.8 on 2026-01-28 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import unicodedata
import re


def normalize_name(name: str) -> str:
    """Normaliza nome do instrumento (lowercase, sem acentos)."""
    name = name.strip().lower()
    # Remove acentos
    name = unicodedata.normalize('NFKD', name)
    name = ''.join([c for c in name if not unicodedata.combining(c)])
    # Remove caracteres especiais (mantém apenas letras, números, espaços, hífens)
    name = re.sub(r'[^a-z0-9\s\-]', '', name)
    # Substitui múltiplos espaços por um único
    name = re.sub(r'\s+', ' ', name)
    return name


def populate_instruments(apps, schema_editor):
    """Popula instrumentos pré-definidos"""
    Instrument = apps.get_model('agenda', 'Instrument')

    BASE_INSTRUMENTS = [
        'Vocal', 'Guitarra', 'Violão', 'Baixo', 'Bateria',
        'Teclado', 'Piano', 'Sintetizador', 'Percussão', 'Cajón',
        'Violino', 'Viola', 'Violoncelo', 'Contrabaixo acústico',
        'Saxofone', 'Trompete', 'Trombone', 'Flauta',
        'Clarinete', 'Gaita', 'Ukulele', 'Banjo',
        'Bandolim', 'DJ', 'Produtor(a)', 'Harmônica',
        'Acordeão', 'Bateria Eletrônica'
    ]

    for display_name in BASE_INSTRUMENTS:
        name = normalize_name(display_name)
        Instrument.objects.get_or_create(
            name=name,
            defaults={
                'display_name': display_name,
                'type': 'predefined',
                'is_approved': True,
                'usage_count': 0
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove instrumentos pré-definidos na reversão da migração"""
    Instrument = apps.get_model('agenda', 'Instrument')
    Instrument.objects.filter(type='predefined').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0029_organization_city_organization_contact_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nome normalizado do instrumento (ex: 'violao')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nome formatado para exibição (ex: 'Violão')",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("predefined", "Pré-definido"),
                            ("community", "Comunidade"),
                        ],
                        default="community",
                        max_length=20,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantos músicos usam este instrumento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, help_text="Se False, precisa aprovação de admin"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que adicionou este instrumento (se community)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instruments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "Instrumentos",
                "ordering": ["-usage_count", "display_name"],
            },
        ),
        migrations.RunPython(populate_instruments, reverse_populate),
    ]
