# Generated by Django 5.2.8 on 2026-01-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0031_add_avatar_url_to_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingRegistration",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="stripe_subscription_id",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="subscription_ends_at",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="subscription_plan",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="subscription_status",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="trial_ends_at",
        ),
        migrations.RemoveField(
            model_name="musician",
            name="trial_started_at",
        ),
    ]
