# Generated by Codex on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0032_remove_subscription_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="subscription_status",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="plan_id",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="current_period_end",
        ),
    ]
