# Generated by Codex on 2026-01-29

from django.db import migrations


def ensure_payment_amount(apps, schema_editor):
    Event = apps.get_model('agenda', 'Event')
    table = Event._meta.db_table
    column = 'payment_amount'

    with schema_editor.connection.cursor() as cursor:
        existing = {
            col.name for col in schema_editor.connection.introspection.get_table_description(cursor, table)
        }

    if column in existing:
        return

    field = Event._meta.get_field(column)
    schema_editor.add_field(Event, field)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0033_remove_org_subscription_and_event_payment'),
    ]

    operations = [
        migrations.RunPython(ensure_payment_amount, migrations.RunPython.noop),
    ]
