# Generated by Codex on 2026-01-29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0034_ensure_event_payment_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("event_delete", "Evento Deletado"),
                            ("event_update_sensitive", "Evento Atualizado (Dados Sensíveis)"),
                            ("availability_delete", "Disponibilidade Deletada"),
                            ("profile_update_sensitive", "Perfil Atualizado (Dados Sensíveis)"),
                            ("musician_delete", "Músico Deletado"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Tipo do recurso afetado (event, musician, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        help_text="ID do recurso afetado",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "timestamp"], name="auditlog_user_ts_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="auditlog_resource_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="auditlog_action_idx"),
        ),
    ]
