# Generated by Django 5.2.8 on 2026-02-01 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0035_create_audit_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Nome da cidade", max_length=100)),
                ("state", models.CharField(help_text="UF (sigla do estado)", max_length=2)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único (URL)", max_length=120, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("partner", "Parceiro"),
                            ("expansion", "Em Expansão"),
                            ("planning", "Em Planejamento"),
                        ],
                        default="planning",
                        help_text="Status da cidade na plataforma",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição ou notas sobre a cidade", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Se a cidade está ativa no sistema"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Prioridade de exibição (maior = mais importante)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin que criou a cidade",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cidade",
                "verbose_name_plural": "Cidades",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active"], name="agenda_city_status_2902e9_idx"
                    ),
                    models.Index(fields=["state"], name="agenda_city_state_342335_idx"),
                ],
                "unique_together": {("name", "state")},
            },
        ),
    ]
