# Generated by OpenCode on 2026-02-03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0036_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="action",
            field=models.CharField(
                max_length=30,
                choices=[
                    ("created", "Criado"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("cancelled", "Cancelado"),
                    ("availability", "Disponibilidade"),
                    ("notification", "Notificacao"),
                    ("user_delete", "Usuario Deletado"),
                    ("organization_delete", "Organizacao Deletada"),
                ],
            ),
        ),
    ]
