# Generated by Codex on 2026-02-03

from django.db import migrations


def ensure_auditlog_table(apps, schema_editor):
    """Create AuditLog table if it is missing."""
    AuditLog = apps.get_model("agenda", "AuditLog")
    table_name = AuditLog._meta.db_table
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name in existing_tables:
        return
    schema_editor.create_model(AuditLog)


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0037_add_user_and_org_delete_to_eventlog"),
    ]

    operations = [
        migrations.RunPython(ensure_auditlog_table, migrations.RunPython.noop),
    ]
