# Generated by Django 5.2.8 on 2026-02-03 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0039_update_eventlog_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Criado"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("cancelled", "Cancelado"),
                    ("availability", "Disponibilidade"),
                    ("notification", "Notificacao"),
                    ("user_delete", "Usuário Deletado"),
                    ("organization_delete", "Organização Deletada"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ContractorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=2, null=True)),
                ("accepted_terms_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contratante",
                "verbose_name_plural": "Contratantes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_date", models.DateField()),
                ("event_type", models.CharField(max_length=120)),
                ("location_city", models.CharField(max_length=100)),
                ("location_state", models.CharField(max_length=2)),
                ("venue_name", models.CharField(blank=True, max_length=150, null=True)),
                ("duration_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("responded", "Respondido"),
                            ("reservation_requested", "Reserva solicitada"),
                            ("reserved", "Reservado"),
                            ("confirmed", "Confirmado"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                            ("declined", "Recusado"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_requests",
                        to="agenda.contractorprofile",
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_requests",
                        to="agenda.musician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Orçamento",
                "verbose_name_plural": "Pedidos de Orçamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField()),
                (
                    "proposed_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Enviada"),
                            ("accepted", "Aceita"),
                            ("declined", "Recusada"),
                            ("expired", "Expirada"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="agenda.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposta de Orçamento",
                "verbose_name_plural": "Propostas de Orçamento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("contractor", "Contratante"),
                            ("musician", "Músico"),
                            ("system", "Sistema"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="agenda.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Reserva",
                "verbose_name_plural": "Eventos de Reserva",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reservado"),
                            ("confirmed", "Confirmado"),
                            ("completed", "Concluído"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="agenda.quoterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "ordering": ["-reserved_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["status", "created_at"], name="agenda_quot_status_2cd250_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["musician", "status"], name="agenda_quot_musicia_a0619f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["contractor", "status"], name="agenda_quot_contrac_eda90a_idx"
            ),
        ),
    ]
