# Generated by Django 5.2.8 on 2026-02-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0040_alter_eventlog_action_contractorprofile_quoterequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, help_text="Descrição da organização", null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, help_text="Site da organização", null=True),
        ),
        migrations.DeleteModel(
            name="ContactRequest",
        ),
    ]
