# Generated by Django 5.2.8 on 2026-02-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0041_alter_organization_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("band", "Banda/Grupo"),
                    ("company", "Contratante"),
                    ("venue", "Casa de Shows"),
                ],
                default="band",
                help_text="Tipo de organização",
                max_length=20,
            ),
        ),
    ]
