# Generated by Django 5.2.8 on 2026-02-04 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0042_alter_organization_org_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_views",
                        to="agenda.contractorprofile",
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_views",
                        to="agenda.musician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visualização de Contato",
                "verbose_name_plural": "Visualizações de Contato",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(fields=["-viewed_at"], name="agenda_cont_viewed__dc5a02_idx"),
                    models.Index(
                        fields=["contractor", "-viewed_at"], name="agenda_cont_contrac_265fee_idx"
                    ),
                    models.Index(
                        fields=["musician", "-viewed_at"], name="agenda_cont_musicia_c15823_idx"
                    ),
                ],
            },
        ),
    ]
