# Generated by Django 5.2.8 on 2026-02-04 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0043_contactview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="musician",
            index=models.Index(
                fields=["is_active", "city", "state"], name="agenda_musi_is_acti_88da64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="musician",
            index=models.Index(
                fields=["is_active", "state"], name="agenda_musi_is_acti_d8a2d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="musician",
            index=models.Index(
                fields=["is_active", "instrument"], name="agenda_musi_is_acti_5f70b2_idx"
            ),
        ),
    ]
