# Generated by Django 5.2.8 on 2026-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0044_musician_agenda_musi_is_acti_88da64_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="musical_genres",
            field=models.JSONField(
                blank=True, default=list, help_text="Lista de gêneros musicais do músico"
            ),
        ),
        migrations.AddField(
            model_name="musicianrequest",
            name="musical_genres",
            field=models.JSONField(
                blank=True, default=list, help_text="Lista de gêneros musicais do músico"
            ),
        ),
    ]
