# Generated by Django 5.2.8 on 2026-02-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0045_add_musical_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_private",
            field=models.BooleanField(
                default=False, help_text="Evento privado (oculta detalhes no calendário público)"
            ),
        ),
    ]
