# Generated by Django 5.2.8 on 2026-02-06 17:03

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0046_event_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="name_changes_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Quantidade de alteracoes de nome no mes"
            ),
        ),
        migrations.AddField(
            model_name="musician",
            name="name_changes_month",
            field=models.DateField(
                default=agenda.models._current_month_start,
                help_text="Mes de referencia para limite de troca de nome",
            ),
        ),
    ]
