# Generated by Django 5.2.8 on 2026-02-09 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0048_remove_maybe_availability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="musician",
            index=models.Index(
                fields=["is_active", "city", "state", "-average_rating"],
                name="agenda_musi_is_acti_1dd96f_idx",
            ),
        ),
    ]
