# Generated by Codex on 2026-02-10

from django.db import migrations


def _normalize_genre(value: str) -> str:
    if not value:
        return ""
    return " ".join(value.strip().lower().split())


def normalize_musical_genres(apps, schema_editor):
    Musician = apps.get_model("agenda", "Musician")
    MusicianRequest = apps.get_model("agenda", "MusicianRequest")

    for Model in (Musician, MusicianRequest):
        to_update = []
        for obj in Model.objects.all().iterator():
            genres = getattr(obj, "musical_genres", None)
            if not isinstance(genres, list):
                continue

            cleaned = []
            for g in genres:
                if not isinstance(g, str):
                    continue
                norm = _normalize_genre(g)
                if norm:
                    cleaned.append(norm)

            # Dedup preservando ordem
            seen = set()
            deduped = []
            for g in cleaned:
                if g in seen:
                    continue
                seen.add(g)
                deduped.append(g)

            if deduped != genres:
                obj.musical_genres = deduped
                to_update.append(obj)

        if to_update:
            Model.objects.bulk_update(to_update, ["musical_genres"])


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0049_add_musician_rating_composite_index"),
    ]

    operations = [
        migrations.RunPython(normalize_musical_genres, migrations.RunPython.noop),
    ]

