# Generated by Django 5.2.8 on 2026-02-19 01:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0050_normalize_musical_genres"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PwaAnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_name", models.CharField(max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("release_label", models.CharField(blank=True, max_length=80)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, max_length=500)),
                ("is_authenticated", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pwa_analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Analytics PWA",
                "verbose_name_plural": "Eventos Analytics PWA",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["event_name", "-occurred_at"], name="pwa_event_name_ts_idx"
                    ),
                    models.Index(
                        fields=["is_authenticated", "-occurred_at"], name="pwa_event_auth_ts_idx"
                    ),
                    models.Index(fields=["release_label"], name="pwa_event_release_idx"),
                ],
            },
        ),
    ]
