# Generated by Django 5.2.8 on 2026-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0052_alter_membership_and_musicianrating_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="is_premium",
            field=models.BooleanField(default=False, help_text="Acesso ao Portal Cultural Premium"),
        ),
    ]
