# Generated by Django 5.2.8 on 2026-02-23 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0053_add_is_premium_to_musician"),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Título do conteúdo", max_length=220)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Resumo curto para exibição no portal",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("edital", "Edital"),
                            ("festival", "Festival"),
                            ("noticia", "Notícia"),
                            ("rouanet", "Lei Rouanet"),
                            ("aldir_blanc", "Aldir Blanc"),
                            ("premio", "Prêmio"),
                            ("other", "Outro"),
                        ],
                        default="edital",
                        help_text="Categoria principal do conteúdo",
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(help_text="UF alvo do conteúdo", max_length=2)),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Cidade alvo (opcional; vazio = conteúdo estadual)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        help_text="Fonte do conteúdo (ex: Prefeitura, MinC, Secult)",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL oficial para mais detalhes",
                        null=True,
                    ),
                ),
                (
                    "deadline_at",
                    models.DateField(
                        blank=True,
                        help_text="Data limite de inscrição (quando aplicável)",
                        null=True,
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True,
                        help_text="Data do evento/festival (quando aplicável)",
                        null=True,
                    ),
                ),
                ("published_at", models.DateField(default=django.utils.timezone.localdate)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cultural_notices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo Cultural Premium",
                "verbose_name_plural": "Conteúdos Culturais Premium",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="culturalnotice",
            index=models.Index(
                fields=["is_active", "state"], name="agenda_cultu_is_acti_f2aa7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="culturalnotice",
            index=models.Index(
                fields=["is_active", "state", "city"], name="agenda_cultu_is_acti_3f57db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="culturalnotice",
            index=models.Index(
                fields=["category", "published_at"], name="agenda_cultu_categor_ec58bc_idx"
            ),
        ),
    ]
