# Generated by Django 5.2.8 on 2026-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0054_culturalnotice"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="culturalnotice",
            new_name="agenda_cult_is_acti_9e662e_idx",
            old_name="agenda_cultu_is_acti_f2aa7f_idx",
        ),
        migrations.RenameIndex(
            model_name="culturalnotice",
            new_name="agenda_cult_is_acti_179697_idx",
            old_name="agenda_cultu_is_acti_3f57db_idx",
        ),
        migrations.RenameIndex(
            model_name="culturalnotice",
            new_name="agenda_cult_categor_48cdc7_idx",
            old_name="agenda_cultu_categor_ec58bc_idx",
        ),
        migrations.AddField(
            model_name="culturalnotice",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, help_text="URL da imagem de capa (og:image ou manual)", null=True
            ),
        ),
    ]
