# Generated by Django 4.2.28 on 2026-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0055_culturalnotice_add_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="artist_type",
            field=models.CharField(
                choices=[("solo", "Solo"), ("dupla", "Dupla"), ("banda", "Banda")],
                default="solo",
                help_text="Tipo de artista/cadastro (solo, dupla ou banda)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="musician",
            name="stage_name",
            field=models.CharField(
                blank=True, help_text="Nome artístico da dupla/banda", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="musicianrequest",
            name="artist_type",
            field=models.CharField(
                choices=[("solo", "Solo"), ("dupla", "Dupla"), ("banda", "Banda")],
                default="solo",
                help_text="Tipo de artista/cadastro (solo, dupla ou banda)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="musicianrequest",
            name="formation_members",
            field=models.JSONField(
                blank=True, default=list, help_text="Integrantes adicionais da dupla/banda"
            ),
        ),
        migrations.AddField(
            model_name="musicianrequest",
            name="stage_name",
            field=models.CharField(
                blank=True, help_text="Nome artístico da dupla/banda", max_length=150, null=True
            ),
        ),
    ]
