# Generated by Django 4.2.28 on 2026-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0056_musician_artist_type_musician_stage_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="portfolio_videos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Vídeos de portfólio (YouTube/Vimeo) para exibição no perfil",
            ),
        ),
    ]
