# Generated by Django 5.2.11 on 2026-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0057_musician_portfolio_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicianrequest",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
