# Generated by Django 5.2.9 on 2025-12-15 17:05

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_organization_event_organization_and_more'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='agenda.organization'),
        ),
        migrations.AddField(
            model_name='gigapplication',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_applications', to='agenda.organization'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                lambda Organization, Gig, GigApplication: (
                    (lambda org: (
                        Gig.objects.filter(organization__isnull=True).update(organization=org),
                        GigApplication.objects.filter(organization__isnull=True).update(organization=org),
                    ))(Organization.objects.filter(name='Banda Principal').first() or Organization.objects.first())
                )
            )(
                apps.get_model('agenda', 'Organization'),
                apps.get_model('marketplace', 'Gig'),
                apps.get_model('marketplace', 'GigApplication'),
            ),
            reverse_code=migrations.RunPython.noop
        ),
    ]
