# Generated by Django 5.2.8 on 2026-02-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_gigchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gigchatmessage",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="marketplace.gigapplication",
            ),
        ),
    ]
