# Generated by Django 5.2.8 on 2026-02-12 14:25

from django.db import migrations


def backfill_application(apps, schema_editor):
    GigChatMessage = apps.get_model("marketplace", "GigChatMessage")
    GigApplication = apps.get_model("marketplace", "GigApplication")

    orphan_messages = GigChatMessage.objects.filter(application__isnull=True)
    gig_ids = orphan_messages.values_list("gig_id", flat=True).distinct()

    for gig_id in gig_ids:
        hired_app = GigApplication.objects.filter(
            gig_id=gig_id, status="hired"
        ).first()
        if hired_app:
            GigChatMessage.objects.filter(
                gig_id=gig_id, application__isnull=True
            ).update(application_id=hired_app.id)
        else:
            GigChatMessage.objects.filter(
                gig_id=gig_id, application__isnull=True
            ).delete()


def reverse_backfill(apps, schema_editor):
    GigChatMessage = apps.get_model("marketplace", "GigChatMessage")
    GigChatMessage.objects.all().update(application=None)


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_add_application_to_gigchatmessage"),
    ]

    operations = [
        migrations.RunPython(backfill_application, reverse_backfill),
    ]
