# Generated by Django 5.2.8 on 2026-02-18 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0050_normalize_musical_genres"),
        ("marketplace", "0005_backfill_chat_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(fields=["status"], name="marketplace_status_999f32_idx"),
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(fields=["created_by"], name="marketplace_created_2c9e06_idx"),
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(fields=["-created_at"], name="marketplace_created_870d01_idx"),
        ),
        migrations.AddIndex(
            model_name="gig",
            index=models.Index(
                fields=["status", "-created_at"], name="marketplace_status_d6cfef_idx"
            ),
        ),
    ]
