# Generated by Django 5.2.11 on 2026-02-12 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_backfill_chat_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigApplicationChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to='marketplace.gigapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_application_chat_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leitura do chat (vaga)',
                'verbose_name_plural': 'Leituras do chat (vagas)',
                'indexes': [models.Index(fields=['application', 'user'], name='marketplace_applica_c50dbb_idx'), models.Index(fields=['user', 'last_read_at'], name='marketplace_user_id_87525b_idx')],
                'unique_together': {('application', 'user')},
            },
        ),
    ]
