# Generated by Django 5.2.8 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_add_quote_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_invite", "Convite para Evento"),
                    ("event_reminder", "Lembrete de Evento"),
                    ("event_confirmed", "Evento Confirmado"),
                    ("event_cancelled", "Evento Cancelado"),
                    ("availability_response", "Resposta de Disponibilidade"),
                    ("quote_request_new", "Novo Pedido de Orçamento"),
                    ("quote_proposal_received", "Proposta Recebida"),
                    ("quote_reservation_created", "Reserva Criada"),
                    ("quote_booking_confirmed", "Reserva Confirmada"),
                    ("marketplace_activity", "Atualizacao de Vagas"),
                ],
                max_length=30,
            ),
        ),
    ]
